apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-jykc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-jykc
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-jykc
  namespace: karthik-jk-dev-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-jykc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-jykc
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/karthik-jk-dev-tenant/my-app/devfile-sample-jykc@sha256:55d1b5e61482a39c16c62ef2db7862137c2fa38b14f3f8cefe064c247b996645
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
